### ISSUE TITLE
Empty SimpleStats page

### ISSUE THREAD

**Issue by ersoma** [Daandelange/kirby3-simplestats#31]
Hey!

I just installed the plugin to a site I'm currently developing. The SimpleStats page shows up in the Panel, but it is completely empty:

![panel_simplestats_1](https://user-images.githubusercontent.com/6604988/218508677-b78cb26e-0624-4151-a230-e5662b0e2e12.png)

An error appeared for the first time I opened the page, but not any more:

<img width="506" alt="panel_simplestats_4" src="https://user-images.githubusercontent.com/6604988/218525620-ac534e8d-c085-4146-9fbc-500c8c0f837b.png">

This may be normal as the site is not yet receiving traffic, but even the current sessions section is empty after I visited a few pages:

![panel_simplestats_2](https://user-images.githubusercontent.com/6604988/218509512-ea8c7a54-5a96-4e84-8d37-413af973c876.png)

It's interesting to note how the date range selector defaults to 1999 and if I open the datepicker and press "Today" it doesn't change the date.

I tried to use the Tracking Tester feature to populate the DB with some data, but got the following error:

![panel_simplestats_3](https://user-images.githubusercontent.com/6604988/218508272-222d1ab0-be6b-4a72-b3ff-650b833c0ac8.png)

The .sqlite file is created successfully.
I'm running PHP 8.2.2 (tried 8.1 as well) and Kirby 3.9.1 on a Ubuntu 20.04.5 LTS server above Dokku 0.29.4.

Do you have any idea what can be the problem?
Thanks!

**Comment by ersoma** [comment]
Update: it's probably PHP, I tried running Kirby on PHP 8.0 and the errors are gone, sessions are picked up and the stats generator works as well.

**Comment by ersoma** [comment]
**Update: I think I found the root cause, PHP version incompatibility.**

When I tried to generate test data under PHP 8.2, I got the following error:
![panel_simplestats_5](https://user-images.githubusercontent.com/6604988/218839998-2ea183a4-f1a0-4eef-bd65-c672a9eb4723.png)
This is because Dynamic Properties are deprecated under PHP 8.2 (https://php.watch/versions/8.2/dynamic-properties-deprecated).

Once I switched to PHP 8.1, the error changed:
<img width="594" alt="panel_simplestats_6" src="https://user-images.githubusercontent.com/6604988/218839566-e15e0d85-05ab-4cc3-8041-6ad2ba97495a.png">
This is because passing null to non-nullable internal function parameters is deprecated under PHP 8.1 (https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation).

In PHP 8.0 the plugin appears to run perfectly, but not above. Unfortunately PHP 8.0 is already past it's active support phase and will only receive security updates for another 9 month (https://www.php.net/supported-versions.php). Kirby fully supports PHP 8.2 since 3.9 (https://getkirby.com/releases/3.9) and it would be amazing to use this plugin with it, under the most up-to-date environment. Would you consider supporting more recent PHP versions soon?
Thanks!

**Comment by nilsmielke** [comment]
This is exactly what happens in my installation (Kirby 3.9.1, PHP 8.1.16). Thank you for leaving this here, @ersoma.

**Comment by Daandelange** [comment]
Hello, thanks for the reports, I'm using PHP 8.0 so it makes sense.  
I'll have a look when I dive back in PHP, or feel free to submit a PR meanwhile.

**Comment by therephil** [comment]
hey @Daandelange and @ersoma there is a pull request there for you to test. 
the way the snowplow/parser issue is fixed is not really a "clean" solution but it should fix the issues for the moment until snowplow-referer-parser/referer-parser/issues/223 is fixed.

**Comment by Daandelange** [comment]
Awesome, thanks for your investigations, looks good at a first glance, I'll soon take some time to test and merge this.

**Comment by Daandelange** [comment]
Php 8.2 should now be supported, Php 8.0 still works too.

**Comment by nilsmielke** [comment]
Thanks for the update. I still cannot change the date range and can only see one date (March 1, 2023). Tested PHP 8.1 and 8.2.
